package com.example.neo4j.audit;

public enum AuditAction {

    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_STATUS_CHANGED,
    EMPLOYEE_TERMINATED,
    EMPLOYEE_MANAGER_CHANGED,
    EMPLOYEE_DEPARTMENT_CHANGED,
    EMPLOYEE_COMPANY_CHANGED,
    EMPLOYEE_SKILLS_CHANGED,
    EMPLOYEE_OFFICE_CHANGED,

    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_DELETED,
    DEPARTMENT_PARENT_CHANGED,
    DEPARTMENT_HEAD_CHANGED,

    OFFICE_CREATED,
    OFFICE_UPDATED,
    OFFICE_DELETED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_STATUS_CHANGED,
    PROJECT_DELETED,
    PROJECT_LEAD_CHANGED,
    PROJECT_DEPARTMENT_CHANGED,
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_UPDATED,
    PROJECT_MEMBER_REMOVED,

    STAFFING_REQUESTED,
    STAFFING_REQUEST_APPROVED,
    STAFFING_REQUEST_REJECTED,
    STAFFING_REQUEST_CANCELLED,

    USER_CREATED,
    USER_EMPLOYEE_LINK_CHANGED,

    LOGIN_SUCCEEDED,
    LOGIN_FAILED
}
