package com.example.neo4j.audit;

public enum AuditAction {

    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_STATUS_CHANGED,
    EMPLOYEE_TERMINATED,
    EMPLOYEE_MANAGER_CHANGED,
    EMPLOYEE_DEPARTMENT_CHANGED,
    EMPLOYEE_COMPANY_CHANGED,
    EMPLOYEE_SKILLS_CHANGED,

    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_DELETED,
    DEPARTMENT_PARENT_CHANGED,
    DEPARTMENT_HEAD_CHANGED,

    USER_CREATED,
    USER_EMPLOYEE_LINK_CHANGED,

    LOGIN_SUCCEEDED,
    LOGIN_FAILED
}
